trigger:
- main

pool:
  vmImage: 'Ubuntu latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'authjwt:latest'
  dotnetVersion: '6.0.412'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      version: '$(dotnetVersion)'

  - script: dotnet restore $(Build.SourcesDirectory)/src/AuthJwt.csproj
    displayName: 'dotnet restore'
    workingDirectory: $(Build.SourcesDirectory)

  - script: dotnet build $(Build.SourcesDirectory)/src/AuthJwt.csproj --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    workingDirectory: $(Build.SourcesDirectory)

  - script: docker build --no-cache -f Dockerfile -t $(dockerId)/$(imageName) .
    displayName: 'docker build $(imageName)'

  - script: |
      docker login -u $(dockerId) -p $(dockerPassword)
      docker push $(dockerId)/$(imageName)
    displayName: 'docker push $(imageName)'
